/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all flight searches
         * @description Returns all searches ordered by most recently created.
         */
        get: operations["listSearches"];
        put?: never;
        /** Create a new flight search */
        post: operations["createSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/searches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single search by ID */
        get: operations["getSearch"];
        put?: never;
        post?: never;
        /** Delete a search and all its snapshots */
        delete: operations["deleteSearch"];
        options?: never;
        head?: never;
        /** Update search status */
        patch: operations["updateSearch"];
        trace?: never;
    };
    "/searches/{id}/alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compute price trend alert
         * @description Analyzes the last 14 days of economy snapshots to detect price trends. Red: 5+ of 7 current-week daily prices exceed previous week. Green: Current week average is 20%+ lower than previous week. Grey: Insufficient data or no significant change.
         */
        get: operations["getAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/searches/{id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Price history for a search */
        get: operations["getPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/searches/{id}/latest-price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Most recent economy snapshot */
        get: operations["getLatestPrice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/searches/{id}/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger live price scrape
         * @description Scrapes Google Flights for both economy and business classes. Silently skips seat classes where the live fetch fails (no mock fallback).
         */
        post: operations["triggerFetch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FlightSearch: {
            id: string;
            /** @description C3 auto-generated name field */
            name?: string;
            /** @description IATA airport code (e.g. "LAX") */
            fromAirport: string;
            /** @description IATA airport code (e.g. "NRT") */
            toAirport: string;
            /** @enum {string} */
            tripType: "one-way" | "round-trip";
            /** Format: date-time */
            outboundDate: string;
            /** Format: date-time */
            returnDate?: string | null;
            maxStops?: number | null;
            /** @default 1 */
            passengersAdults: number;
            language?: string;
            currency?: string;
            /** @enum {string} */
            searchStatus: "active" | "disabled";
            isTestData?: boolean;
            /** @description C3 entity version (optimistic locking) */
            version?: number;
            meta?: components["schemas"]["Meta"];
        };
        PriceSnapshot: {
            id: string;
            /** @description C3 auto-generated name field */
            name?: string;
            /** @description Parent search (full entity or ID reference) */
            flightSearch: components["schemas"]["FlightSearch"] | {
                id?: string;
            };
            /** @enum {string} */
            seatClass: "economy" | "business";
            /** @description Price in cents (e.g. 85000 = $850) */
            price: number;
            /** @description IATA airline codes */
            airlineCodes?: string[];
            airlineNames?: string[];
            /** @description "direct", "1 stop", etc. */
            flightType?: string;
            durationMinutes?: number | null;
            /** Format: date-time */
            fetchedAt: string;
            version?: number;
            meta?: components["schemas"]["Meta"];
        };
        AlertResult: {
            searchId: string;
            /** @enum {string} */
            status: "red" | "green" | "grey";
            /** @description Human-readable alert description */
            message: string;
            /** @description Average daily min price this week (cents) */
            currentWeekAvg?: number | null;
            /** @description Average daily min price last week (cents) */
            previousWeekAvg?: number | null;
            /** @description Week-over-week percent change */
            percentChange?: number | null;
            /** @description Days where current week price > previous week */
            daysRising?: number | null;
            /** @description Name of cheapest airline from latest snapshot */
            cheapestAirline?: string | null;
            /** @description Protobuf-encoded Google Flights search URL */
            googleFlightsUrl?: string | null;
        };
        SearchCreateInput: {
            /** @description IATA airport code */
            fromAirport: string;
            /** @description IATA airport code */
            toAirport: string;
            /**
             * @default one-way
             * @enum {string}
             */
            tripType: "one-way" | "round-trip";
            /** Format: date */
            outboundDate: string;
            /** Format: date */
            returnDate?: string | null;
            maxStops?: number | null;
            /** @default 1 */
            passengersAdults: number;
            /** @default USD */
            currency: string;
        };
        Meta: {
            /** Format: date-time */
            created?: string;
            /** Format: date-time */
            updated?: string;
        };
        ApiError: {
            error?: string;
            status?: number;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description FlightSearch entity ID */
        SearchId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSearches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of flight searches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSearch"][];
                };
            };
        };
    };
    createSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchCreateInput"];
            };
        };
        responses: {
            /** @description The created search with searchStatus "active" */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSearch"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getSearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FlightSearch entity ID */
                id: components["parameters"]["SearchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The search entity with all fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSearch"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteSearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FlightSearch entity ID */
                id: components["parameters"]["SearchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted successfully (empty body) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FlightSearch entity ID */
                id: components["parameters"]["SearchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    searchStatus: "active" | "disabled";
                };
            };
        };
        responses: {
            /** @description The updated search */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSearch"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FlightSearch entity ID */
                id: components["parameters"]["SearchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alert result with trend analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResult"];
                };
            };
        };
    };
    getPrices: {
        parameters: {
            query?: {
                /** @description Filter by seat class (omit for all classes) */
                seatClass?: "economy" | "business";
            };
            header?: never;
            path: {
                /** @description FlightSearch entity ID */
                id: components["parameters"]["SearchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of price snapshots ordered by fetchedAt ascending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSnapshot"][];
                };
            };
        };
    };
    getLatestPrice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FlightSearch entity ID */
                id: components["parameters"]["SearchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest economy snapshot, or null if none exist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSnapshot"] | null;
                };
            };
        };
    };
    triggerFetch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description FlightSearch entity ID */
                id: components["parameters"]["SearchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newly fetched snapshots (0-2 items depending on scrape success) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSnapshot"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
